### ISSUE TITLE
the readme needs fixing up

### ISSUE THREAD

**Issue by jon-shanks** [UKHomeOffice/docker-elasticsearch#1]
docker run --name es_thing --rm=true -e 'PROXY_SERVICE_HOST=google.com' -e 'PROXY_SERVICE_PORT=80' -p 9200:9200 -p 9300:9300 quay.io/ukhomeofficedigital/elasticsearch:v0.1.0

isn't the right options ;-)

**Comment by lewismarshall** [comment]
Sorted by PR: https://github.com/UKHomeOffice/docker-elasticsearch/pull/2
