### ISSUE TITLE
Enable fs snapshots

### ISSUE THREAD

**Issue by daniel78uk** [UKHomeOffice/docker-elasticsearch#39]
Hi,

I tried to use this image to do `fs` snapshots of the database.
Although one variable is missing on your yml configuration, https://github.com/UKHomeOffice/docker-elasticsearch/blob/master/config/elasticsearch.yml#L10.
At the moment I have overridden an added it manually through a config map:
` path.repo: [ "${PATH_DATA}/backups" ]`
Let me know if this is something you are willing to implement in the future

**Comment by marcinc** [comment]
I'm not sure this is relevant. Please refer to README.md (Configuration section). You can provide your own data path by providing custom `$PATH_DATA`. 

```PATH_DATA: Path where ES stores its data. Default: /data.```
